#!/bin/bash
# Git pre-commit hook wrapper for pre-commit
# Install: python3 -m pip install --user pre-commit && python3 -m pre_commit install --install-hooks

set -e

exec python3 -m pre_commit run --hook-stage commit
