fail_fast: false

repos:
  - repo: https://github.com/pocc/pre-commit-hooks
    rev: v1.3.5
    hooks:
      - id: clang-format
        args: [-i]

      - id: clang-tidy

  - repo: local
    hooks:
      - id: cpp-naming-convention
        name: C++ Naming Convention Check
        entry: ./scripts/run_naming_check.sh
        language: system
        pass_filenames: false