name: C++ Lint

on:
  push:
  pull_request:

jobs:
  clang-tidy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y clang-tidy cmake

      - name: Configure project and export compilation database
        run: |
          mkdir -p src/sprites/build
          cmake -S src/sprites -B src/sprites/build -DCMAKE_EXPORT_COMPILE_COMMANDS=ON

      - name: Run clang-tidy
        run: |
<<<<<<< HEAD
          find src/sprites -type f \( -name "*.cpp" -o -name "*.h" \) | \
            xargs -r clang-tidy --quiet --warnings-as-errors=* -p src/sprites/build --
=======
          find . \
            -type f \( -name "*.cpp" -o -name "*.h" \) | \
          xargs -r clang-tidy --quiet --warnings-as-errors=*
>>>>>>> refs/remotes/origin/feat/linter2
