name: C++ Lint

on:
  push:
  pull_request:

jobs:
  clang-tidy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y clang-tidy
        
      - name: Run clang-tidy
        run: |
          find . -type d -name build -prune -o -type d -name cmake_build -prune -o -name "*.cpp" -print -o -name "*.h" -print | xargs clang-tidy --quiet --warnings-as-errors=*
